#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_PLUGINS_DIR="dotbot-plugins"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname $BASH_SOURCE[0])" && pwd)"

cd $BASEDIR
git -C $DOTBOT_DIR submodule sync --quiet --recursive
git submodule update --init --recursive $DOTBOT_DIR

$DOTBOT_DIR/$DOTBOT_BIN -c $CONFIG --plugin-dir $DOTBOT_PLUGINS_DIR $@